package neverov.euler.problems

import neverov.euler.EulerProblem

/**
 * User: Neverrav
 * Date: 25.08.12
 * Time: 13:30
 */
class Problem45 extends EulerProblem{
  val description = "Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:\n" +
    "Triangle\t \tTn=n(n+1)/2\t \t1, 3, 6, 10, 15, ...\n" +
    "Pentagonal\t \tPn=n(3n1)/2\t \t1, 5, 12, 22, 35, ...\n" +
    "Hexagonal\t \tHn=n(2n1)\t \t1, 6, 15, 28, 45, ...\n" +
    "It can be verified that T285 = P165 = H143 = 40755.\n" +
    "Find the next triangle number that is also pentagonal and hexagonal."

  val solved = false

  def solve = {
        "error"
  }
}
